app = "leadleader-ty-demo"
primary_region = "iad"

[env]
  PORT = "8080"

[experimental]
  allowed_public_ports = [8080]

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [services.http_checks]
    path = "/_health"
    method = "get"
    interval = 30000
    timeout = 5000
    grace_period = 10000
  [[services.ports]]
    handlers = ["http"]
    port = 80

[http_service]
  internal_port = 8080
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = "30s"
    method = "get"
    path = "/_health"
    timeout = "5s"
    grace_period = "10s"
