app = "leadleader-ty-demo"
primary_region = "iad"

[env]
  PORT = "8080"

[experimental]
  allowed_public_ports = [8080]

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [services.http_checks]
    path = "/_health"
    method = "get"
    interval = 30000
    timeout = 5000
    grace_period = 10000
  [[services.ports]]
    handlers = ["http"]
    port = 80
